# Generated by Django 4.0.2 on 2022-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('votes', models.PositiveIntegerField()),
            ],
        ),
    ]
